services:
  nextjs:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - go-gateway-api_default

networks:
  go-gateway-api_default:
    external: true
